FROM python:3.9-slim

WORKDIR /usr/src/app

COPY ./requirements.txt ./

RUN apt-get update && apt-get -y install \
    vim\
    gcc

RUN pip install -r ./requirements.txt --no-cache-dir

CMD [ "python", "./src/main.py" ]